const Options = [
  "Technology",
  "Games",
  "Lifestyle",
  "Food",
  "Featured",
  "Hot Posts",
  "Business",
  "Robotics",
  "AI",
  "Computer",
  "Phones",
  "Travel",
  "Health",
  "Sports",
  "Education",
  "Science",
  "Fashion",
  "Music",
  "Art",
  "Movies",
  "Books",
  "Home",
].map((option) => ({ value: option.toLowerCase(), label: option }));

export default Options;
